a:2:{s:7:"current";a:7:{s:4:"date";a:2:{s:7:"created";i:1371127370;s:8:"modified";i:1374638659;}s:11:"last_change";b:0;s:4:"user";s:0:"";s:7:"creator";s:0:"";s:8:"internal";a:2:{s:5:"cache";b:1;s:3:"toc";b:1;}s:11:"description";a:1:{s:8:"abstract";s:275:"Exception Handling

When Python experiences an exceptional event. This is throwing an exception or raising an exception 

Raise: We invoke these to trigger exceptions on our terms 

Throw: Exceptions which were not handled. 


Raise statement: Manually generate an exception.";}s:8:"relation";a:1:{s:10:"firstimage";s:24:"mani:notes:callstack.png";}}s:10:"persistent";a:4:{s:4:"date";a:1:{s:7:"created";i:1371127370;}s:11:"last_change";b:0;s:4:"user";s:0:"";s:7:"creator";s:0:"";}}